# Non Graded Challange 4

Name : Rahmat Fadhli Syauqi

Batch : 11

In [3]:
import numpy as np
from numpy import array 
from numpy.linalg import eig,inv,det

## SOAL 1

1. Apakah adalah A eigenvector dari B ? Jika Iya, berapakah eigenvalue-nya?


In [12]:
A = np.array([1,3])
A


array([1, 3])

In [11]:
B = np.array([[1,-1], [6,4]])
B

array([[ 1, -1],
       [ 6,  4]])

In [17]:
#Apakah B merupakan eigenvector dari A?
B@A/A


array([-2.,  6.])

Dari hasil diatas dapat disimpulkan baha B bukan merupakan eigenvector dari A

In [16]:
X = eigvec @ np.diag(eigval) @ np.linalg.inv(eigvec)
X

array([[ 1.-4.70796047e-17j, -1.-3.25661782e-18j],
       [ 6.+3.20635860e-16j,  4.-7.82938924e-17j]])