# Non Graded Challange 4

Name : Rahmat Fadhli Syauqi

Batch : 11

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Assignment Instructions

- Buatlah Tensor dibawah ini dengan Python:

$$ \begin{bmatrix} \begin{bmatrix} 23 & 50 \ 7 & 12 \ \end{bmatrix} \begin{bmatrix} 57 & 67 \ 99 & 43 \end{bmatrix} \ \begin{bmatrix} 75 & 21 \ 57 & 12 \ \end{bmatrix} \begin{bmatrix} 87 & 26 \ 18 & 84 \end{bmatrix} \end{bmatrix} $$

- Lakukan perkalian terhadap matrix berikut:

$$ A = \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} $$

- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} $$

## Soal 1 ##

Buatlah Tensor dibawah ini dengan Python:

In [13]:
Tensor = np.array ([[[[23,50], [7,12]],
                    [[57, 67], [99,43]]],
                    [[[75, 21],[57, 12]],
                    [[87,26], [18,84]]]])
Tensor

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 84]]]])

In [15]:
Tensor.shape

(2, 2, 2, 2)

## Soal 2 ##

Lakukan perkalian terhadap matrix berikut:



In [23]:
A = np.array([[23,50,19],
     [7,12,109],
     [57,67,98]])
B = np.array([17,22,19])
print(A)

print(B)


[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[17 22 19]


In [20]:
A @ B #Perkalian A dgn B

array([1852, 2454, 4305])

## Soal 3 ##

Lakukan transpose, hitung determinanm dab inverse terhadap matrix di bawah ini


In [24]:
A = np.array([[23,50,19],
              [7,12,109],
              [57,67,98]])

In [25]:
#Transpose
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [26]:
#Determinant 
np.linalg.det(A)

131344.0000000002

In [27]:
#Inverse
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])